import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const sb=createClient('https://ittixiicaeizihyzawju.supabase.co','sb_publishable_SIlfF6-ctdJL2WTg3eTlKQ_5F3LKsSl');
const fmt=n=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:0}).format(Number(n||0));
const money=n=>`${fmt(n)} ر.س`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const pill=document.querySelector('.header-actions .pill');
const avatar=document.querySelector('.avatar');
let state={loading:true,error:null,user:null,membership:null,tenant:null,trial:null,subscription:null,channel:null,health:null,snapshots:[],integrations:[],counts:{conversations:0,leads:0,qualified:0,orders:0}};

async function count(table,tenantId,extra){let q=sb.from(table).select('*',{count:'exact',head:true}).eq('tenant_id',tenantId);if(extra)q=extra(q);const {count,error}=await q;if(error)throw error;return count||0}
async function load(){
  const {data:{session}}=await sb.auth.getSession();
  if(!session){location.replace('/login.html');return}
  state.user=session.user;avatar.textContent=(session.user.email||'V').slice(0,1).toUpperCase();
  try{
    const {data:members,error:me}=await sb.from('tenant_members').select('tenant_id,role,tenants(id,name,status,business_type,timezone,locale)').eq('user_id',session.user.id).limit(1);if(me)throw me;
    if(!members?.length){state.loading=false;state.error='ACCOUNT_NOT_LINKED';renderCurrent();return}
    state.membership=members[0];state.tenant=members[0].tenants;const tid=state.membership.tenant_id;
    const [trial,sub,channel,health,snaps,ints,conv,leads,qualified,orders]=await Promise.all([
      sb.from('trials').select('id,status,starts_at,ends_at,plan_id').eq('tenant_id',tid).order('created_at',{ascending:false}).limit(1).maybeSingle(),
      sb.from('subscriptions').select('id,status,plan_id,current_period_start,current_period_end,plans(id,name,setup_fee,monthly_fee,currency,features)').eq('tenant_id',tid).order('created_at',{ascending:false}).limit(1).maybeSingle(),
      sb.from('channel_accounts').select('connection_status,provisioning_status,transport_verified_at,last_inbound_at,last_outbound_at,last_error_code,capabilities,metadata').eq('tenant_id',tid).eq('channel','whatsapp').order('created_at',{ascending:false}).limit(1).maybeSingle(),
      sb.from('customer_health').select('*').eq('tenant_id',tid).maybeSingle(),
      sb.from('revenue_snapshots').select('*').eq('tenant_id',tid).order('snapshot_date',{ascending:false}).limit(30),
      sb.from('integration_health').select('integration_type,integration_key,status,last_success_at,last_failure_at,error_code,checked_at').or(`tenant_id.eq.${tid},tenant_id.is.null`).order('checked_at',{ascending:false}),
      count('conversations',tid),count('leads',tid),count('leads',tid,q=>q.eq('stage','qualified')),count('orders',tid)
    ]);
    for(const r of [trial,sub,channel,health,snaps,ints])if(r.error)throw r.error;
    state.trial=trial.data;state.subscription=sub.data;state.channel=channel.data;state.health=health.data;state.snapshots=snaps.data||[];state.integrations=ints.data||[];state.counts={conversations:conv,leads,qualified,orders};state.loading=false;
  }catch(e){console.error(e);state.loading=false;state.error=e.message||String(e)}
  renderCurrent();
}
function latest(){return state.snapshots[0]||{attributed_revenue:0,recovered_revenue:0,upsell_revenue:0,estimated_hours_saved:0}}
function daysLeft(){if(!state.trial?.ends_at)return null;return Math.max(0,Math.ceil((new Date(state.trial.ends_at)-new Date())/86400000))}
function trialProgress(){if(!state.trial?.starts_at||!state.trial?.ends_at)return 0;const s=new Date(state.trial.starts_at),e=new Date(state.trial.ends_at),n=new Date();return Math.min(100,Math.max(0,Math.round(((n-s)/(e-s))*100)))}
function channelStatus(){return state.channel?.connection_status||'pending'}
function badge(){if(state.loading){pill.textContent='جارٍ التحميل';pill.className='pill'}else if(state.error==='ACCOUNT_NOT_LINKED'){pill.textContent='بانتظار ربط الحساب';pill.className='pill warn'}else if(state.trial?.status==='active'){pill.textContent=`التجربة: ${daysLeft()} أيام`;pill.className='pill good'}else if(state.subscription?.status==='active'){pill.textContent='الاشتراك: نشط';pill.className='pill good'}else{pill.textContent='الحالة: '+(state.subscription?.status||state.tenant?.status||'onboarding');pill.className='pill warn'}}
function shell(content){if(state.loading)return `<div class="card empty">جارٍ تحميل بيانات نشاطك بأمان…</div>`;if(state.error==='ACCOUNT_NOT_LINKED')return `<div class="card empty"><b>تم تسجيل الدخول بنجاح</b><br><br>هذا المستخدم لم يُربط بعد بأي Tenant. لن نعرض أي بيانات حتى يتم تعيين عضوية صريحة في Vaultify.</div>`;if(state.error)return `<div class="card empty">تعذر تحميل البيانات: ${esc(state.error)}</div>`;return content}

const views={
overview:()=>shell((()=>{const m=latest(),total=Number(m.attributed_revenue||0)+Number(m.recovered_revenue||0)+Number(m.upsell_revenue||0);return `<div class="hero"><div class="card hero-main"><div class="eyebrow">قيمة Vaultify المثبتة لنشاطك</div><div class="big">${money(total)}</div><div class="sub">هذه القيمة تُحسب من بياناتك الفعلية فقط: إيراد منسوب + مسترجع + Upsell.</div></div><div class="card"><div class="eyebrow">${esc(state.tenant.name)}</div><div class="status-row"><span>الحالة</span><b>${esc(state.subscription?.status||state.tenant.status)}</b></div><div class="status-row"><span>WhatsApp</span><b>${esc(channelStatus())}</b></div><div class="status-row"><span>Health Score</span><b>${state.health?.health_score??'—'}/100</b></div></div></div><div class="grid"><div class="card metric"><span class="label">الإيراد المنسوب</span><strong>${money(m.attributed_revenue)}</strong></div><div class="card metric"><span class="label">الإيراد المسترجع</span><strong>${money(m.recovered_revenue)}</strong></div><div class="card metric"><span class="label">Upsell</span><strong>${money(m.upsell_revenue)}</strong></div><div class="card metric"><span class="label">ساعات موفرة</span><strong>${fmt(m.estimated_hours_saved)}</strong></div></div><div class="section-title"><h2>المبيعات والعملاء</h2></div><div class="grid"><div class="card metric"><span class="label">المحادثات</span><strong>${fmt(state.counts.conversations)}</strong></div><div class="card metric"><span class="label">Leads</span><strong>${fmt(state.counts.leads)}</strong></div><div class="card metric"><span class="label">Qualified</span><strong>${fmt(state.counts.qualified)}</strong></div><div class="card metric"><span class="label">طلبات/حجوزات</span><strong>${fmt(state.counts.orders)}</strong></div></div><div class="section-title"><h2>حالة WhatsApp</h2></div><div class="card"><div class="status-row"><span>Provisioning</span><b>${esc(state.channel?.provisioning_status||'pending')}</b></div><div class="status-row"><span>Transport verified</span><b>${state.channel?.transport_verified_at?'نعم':'لا'}</b></div><div class="status-row"><span>Connection</span><b>${esc(channelStatus())}</b></div><div class="status-row"><span>آخر وارد</span><b>${state.channel?.last_inbound_at?new Date(state.channel.last_inbound_at).toLocaleString('ar-SA'):'—'}</b></div></div>`})()),
trial:()=>shell(state.trial?`<div class="hero"><div class="card hero-main"><div class="eyebrow">تجربة Vaultify المجانية</div><div class="big">${daysLeft()} أيام</div><div class="sub">بدأت من أول Transport verified حقيقي. لا يوجد Reset Trial من واجهة العميل.</div><div class="progress"><span style="width:${trialProgress()}%"></span></div></div><div class="card"><div class="status-row"><span>الحالة</span><b>${esc(state.trial.status)}</b></div><div class="status-row"><span>البداية</span><b>${new Date(state.trial.starts_at).toLocaleString('ar-SA')}</b></div><div class="status-row"><span>النهاية</span><b>${new Date(state.trial.ends_at).toLocaleString('ar-SA')}</b></div></div></div>`:`<div class="card empty">لم تبدأ تجربة الـ7 أيام بعد. ستبدأ تلقائيًا فقط بعد أول inbound حقيقي يثبت اتصال WhatsApp.</div>`),
billing:()=>shell(`<div class="section-title"><h2>الاشتراك والفوترة</h2></div><div class="card"><div class="status-row"><span>الحالة</span><b>${esc(state.subscription?.status||'لا يوجد اشتراك بعد')}</b></div><div class="status-row"><span>الخطة</span><b>${esc(state.subscription?.plans?.name||state.subscription?.plan_id||'—')}</b></div><div class="status-row"><span>السعر الشهري</span><b>${state.subscription?.plans?money(state.subscription.plans.monthly_fee):'—'}</b></div><div class="status-row"><span>رسوم التأسيس</span><b>${state.subscription?.plans?money(state.subscription.plans.setup_fee):'—'}</b></div></div><div class="section-title"><h2>مسارات التوسعة</h2></div><div class="grid two"><div class="card"><b>Growth Upgrade</b><p class="sub">يظهر تلقائيًا عند وجود Usage + ROI signal مناسب.</p></div><div class="card"><b>Annual Prepay</b><p class="sub">جاهز معماريًا لزيادة التحصيل النقدي عند ربط بوابة الدفع.</p></div></div>`),
integrations:()=>shell(`<div class="section-title"><h2>صحة التكاملات</h2></div><div class="grid two">${state.integrations.length?state.integrations.map(x=>`<div class="card status-row"><span><i class="dot ${x.status==='healthy'?'good':'warn'}"></i>${esc(x.integration_key||x.integration_type)}</span><b>${esc(x.status)}</b></div>`).join(''):'<div class="card empty">لا توجد قراءات Integration Health لهذا الـTenant بعد.</div>'}</div><div class="section-title"><h2>WhatsApp Transport</h2></div><div class="card"><div class="status-row"><span>Provisioning</span><b>${esc(state.channel?.provisioning_status||'pending')}</b></div><div class="status-row"><span>Connection</span><b>${esc(channelStatus())}</b></div><div class="status-row"><span>Transport verified</span><b>${state.channel?.transport_verified_at?'نعم':'لا'}</b></div><div class="status-row"><span>آخر خطأ</span><b>${esc(state.channel?.last_error_code||'—')}</b></div></div>`)
};
const titles={overview:'مركز الإيرادات',trial:'التجربة المجانية',billing:'الاشتراك والفوترة',integrations:'التكاملات'};
function render(name){badge();document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const el=document.getElementById(name);el.innerHTML=views[name]();el.classList.add('active');document.getElementById('pageTitle').textContent=titles[name];location.hash=name}
function renderCurrent(){render(location.hash.slice(1) in views?location.hash.slice(1):'overview')}
document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)render(b.dataset.view)});
renderCurrent();load();
