import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const URL='https://ittixiicaeizihyzawju.supabase.co';
const KEY='sb_publishable_SIlfF6-ctdJL2WTg3eTlKQ_5F3LKsSl';
const sb=createClient(URL,KEY,{auth:{detectSessionInUrl:true,persistSession:true,autoRefreshToken:true}});
const fmt=n=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:0}).format(Number(n||0));
const money=n=>`${fmt(n)} ر.س`;
const dt=x=>x?new Date(x).toLocaleString('ar-SA'):'—';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let state={};
const $=s=>document.querySelector(s);
function badge(){const p=$('#entitlementPill');if(state.trial?.status==='active'){p.textContent=`التجربة: ${daysLeft()} أيام`;p.className='pill good'}else if(state.subscription?.status==='active'){p.textContent='الاشتراك نشط';p.className='pill good'}else{p.textContent=state.channel?.connection_status==='connected'?'WhatsApp متصل':'بانتظار WhatsApp';p.className='pill warn'}}
function daysLeft(){if(!state.trial?.ends_at)return 7;return Math.max(0,Math.ceil((new Date(state.trial.ends_at)-Date.now())/86400000))}
function row(a,b){return `<div class="status-row"><span>${esc(a)}</span><b>${esc(b)}</b></div>`}
function empty(t='لا توجد بيانات بعد.'){return `<div class="card empty">${esc(t)}</div>`}
function table(headers,rows){if(!rows?.length)return empty();return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function totalValue(){const m=state.revenue?.latest||{};return Number(m.attributed_revenue||0)+Number(m.recovered_revenue||0)+Number(m.upsell_revenue||0)}
const views={
overview(){const m=state.revenue?.latest||{};return `<div class="hero"><div class="card hero-main"><div class="eyebrow">القيمة المثبتة بواسطة Vaultify</div><div class="big">${money(totalValue())}</div><div class="sub">إيراد منسوب + مسترجع + Upsell. الأرقام لا تُحتسب إلا من بيانات النظام الفعلية.</div></div><div class="card">${row('النشاط',state.tenant?.name||'—')}${row('WhatsApp',state.channel?.connection_status||'pending')}${row('Health Score',`${state.health?.health_score??'—'}/100`)}${row('Churn Risk',state.health?.churn_risk||'—')}</div></div><div class="grid"><div class="card metric"><span>الإيراد المنسوب</span><strong>${money(m.attributed_revenue)}</strong></div><div class="card metric"><span>الإيراد المسترجع</span><strong>${money(m.recovered_revenue)}</strong></div><div class="card metric"><span>Upsell</span><strong>${money(m.upsell_revenue)}</strong></div><div class="card metric"><span>ساعات موفرة</span><strong>${fmt(m.estimated_hours_saved)}</strong></div></div><div class="section-title"><h2>نبض المبيعات</h2></div><div class="grid"><div class="card metric"><span>جهات الاتصال</span><strong>${fmt(state.counts?.contacts)}</strong></div><div class="card metric"><span>Leads</span><strong>${fmt(state.counts?.leads)}</strong></div><div class="card metric"><span>Qualified</span><strong>${fmt(state.counts?.qualified_leads)}</strong></div><div class="card metric"><span>الطلبات</span><strong>${fmt(state.counts?.orders)}</strong></div></div>`},
crm(){const ls=state.leads||[];const cs=state.contacts||[];return `<div class="grid"><div class="card metric"><span>إجمالي Leads</span><strong>${fmt(state.counts?.leads)}</strong></div><div class="card metric"><span>Qualified</span><strong>${fmt(state.counts?.qualified_leads)}</strong></div><div class="card metric"><span>جهات الاتصال</span><strong>${fmt(state.counts?.contacts)}</strong></div><div class="card metric"><span>قيمة الفرص</span><strong>${money(ls.reduce((a,x)=>a+Number(x.estimated_value||0),0))}</strong></div></div><div class="section-title"><h2>آخر الفرص</h2></div>${table(['العميل','المرحلة','النقاط','القيمة','المتابعة'],ls.map(x=>`<tr><td><b>${esc(x.contacts?.name||'بدون اسم')}</b><small>${esc(x.contacts?.phone||'')}</small></td><td><span class="tag">${esc(x.stage)}</span></td><td>${fmt(x.score)}</td><td>${money(x.estimated_value)}</td><td>${dt(x.next_follow_up_at)}</td></tr>`))}<div class="section-title"><h2>آخر جهات الاتصال</h2></div>${table(['الاسم','الجوال','المدينة','الموافقة'],cs.map(x=>`<tr><td>${esc(x.name||'—')}</td><td>${esc(x.phone||'—')}</td><td>${esc(x.city||'—')}</td><td>${esc(x.consent_status||'—')}</td></tr>`))}`},
conversations(){const cs=state.conversations||[];return `<div class="grid"><div class="card metric"><span>المحادثات</span><strong>${fmt(state.counts?.conversations)}</strong></div><div class="card metric"><span>آخر وارد</span><strong class="sm">${dt(state.channel?.last_inbound_at)}</strong></div><div class="card metric"><span>آخر صادر</span><strong class="sm">${dt(state.channel?.last_outbound_at)}</strong></div><div class="card metric"><span>القناة</span><strong>WhatsApp</strong></div></div><div class="section-title"><h2>المحادثات الأخيرة</h2></div>${table(['العميل','القناة','الحالة','آخر رسالة'],cs.map(x=>`<tr><td><b>${esc(x.contacts?.name||'بدون اسم')}</b><small>${esc(x.contacts?.phone||'')}</small></td><td>${esc(x.channel)}</td><td>${esc(x.status)}</td><td>${dt(x.last_message_at)}</td></tr>`))}`},
roi(){const h=state.revenue?.history||[];const m=state.revenue?.latest||{};const roi=Number(state.health?.roi_30d||0);return `<div class="hero"><div class="card hero-main"><div class="eyebrow">ROI خلال 30 يوم</div><div class="big">${fmt(roi)}%</div><div class="sub">هدف هذه الصفحة: إثبات أن Vaultify يحقق قيمة مالية قابلة للقياس، وليس مجرد ردود آلية.</div></div><div class="card">${row('Attributed',money(m.attributed_revenue))}${row('Recovered',money(m.recovered_revenue))}${row('Upsell',money(m.upsell_revenue))}${row('Hours Saved',fmt(m.estimated_hours_saved))}</div></div><div class="section-title"><h2>آخر 30 لقطة إيراد</h2></div>${table(['التاريخ','Leads','طلبات','منسوب','مسترجع','Upsell'],h.map(x=>`<tr><td>${esc(x.snapshot_date)}</td><td>${fmt(x.leads_count)}</td><td>${fmt(x.orders_count)}</td><td>${money(x.attributed_revenue)}</td><td>${money(x.recovered_revenue)}</td><td>${money(x.upsell_revenue)}</td></tr>`))}`},
trial(){if(!state.trial)return `<div class="hero"><div class="card hero-main"><div class="eyebrow">7 أيام فقط</div><div class="big">تبدأ بعد التشغيل الفعلي</div><div class="sub">لن نخسر من أيام العميل أثناء إعداد Meta. بداية التجربة تُسجل Server-side بعد أول inbound موثّق.</div></div><div class="card">${row('الحالة الحالية','لم تبدأ بعد')}${row('WhatsApp',state.channel?.connection_status||'pending')}</div></div><div class="grid"><div class="card"><b>اليوم 1 — تأكيد التشغيل</b><p>inbound + AI + reply</p></div><div class="card"><b>اليوم 3 — إثبات قيمة</b><p>تقرير Leads والإيراد</p></div><div class="card"><b>قبل 48/24 ساعة</b><p>تحويل للمدفوع</p></div><div class="card"><b>نهاية اليوم 7</b><p>Paywall مع حفظ البيانات</p></div></div>`;return `<div class="hero"><div class="card hero-main"><div class="eyebrow">التجربة المجانية</div><div class="big">${daysLeft()} أيام</div><div class="sub">تنتهي ${dt(state.trial.ends_at)}</div></div><div class="card">${row('المحادثات',fmt(state.trial.conversations_count))}${row('Qualified',fmt(state.trial.qualified_leads_count))}${row('Recovered',fmt(state.trial.recovered_leads_count))}${row('Revenue',money(state.trial.attributed_revenue))}</div></div>`},
billing(){const s=state.subscription,p=state.payments||[],i=state.invoices||[],o=state.orders||[];return `<div class="hero"><div class="card hero-main"><div class="eyebrow">الاشتراك</div><div class="big">${esc(s?.plans?.name||s?.plan_id||'لم يبدأ')}</div><div class="sub">الدفع الفعلي سيُربط ببوابة الدفع لاحقًا؛ طبقة الاشتراك والفواتير جاهزة من الآن.</div></div><div class="card">${row('الحالة',s?.status||'—')}${row('شهري',s?.plans?money(s.plans.monthly_fee):'—')}${row('تأسيس',s?.plans?money(s.plans.setup_fee):'—')}${row('المزود',s?.provider||'غير مربوط')}</div></div><div class="section-title"><h2>المدفوعات</h2></div>${table(['المزود','النوع','الحالة','المبلغ','التاريخ'],p.map(x=>`<tr><td>${esc(x.provider||'—')}</td><td>${esc(x.payment_type||'—')}</td><td>${esc(x.status)}</td><td>${money(x.amount)}</td><td>${dt(x.occurred_at||x.created_at)}</td></tr>`))}<div class="section-title"><h2>الفواتير</h2></div>${table(['الفاتورة','الحالة','الإجمالي','الاستحقاق'],i.map(x=>`<tr><td>${esc(x.invoice_number||'—')}</td><td>${esc(x.status)}</td><td>${money(x.total)}</td><td>${dt(x.due_at)}</td></tr>`))}<div class="section-title"><h2>الطلبات</h2></div>${table(['العميل','الحالة','النوع','المبلغ'],o.map(x=>`<tr><td>${esc(x.contacts?.name||'—')}</td><td>${esc(x.status)}</td><td>${esc(x.order_type)}</td><td>${money(x.amount)}</td></tr>`))}`},
automation(){const ints=state.integrations||[],jobs=state.automation_jobs||[],ret=state.retention_actions||[],refs=state.referrals||[];return `<div class="grid"><div class="card metric"><span>Integration Health</span><strong>${ints.filter(x=>x.status==='healthy').length}/${ints.length}</strong></div><div class="card metric"><span>Automation Jobs</span><strong>${jobs.length}</strong></div><div class="card metric"><span>Retention Actions</span><strong>${ret.length}</strong></div><div class="card metric"><span>Referrals</span><strong>${refs.length}</strong></div></div><div class="section-title"><h2>صحة التكاملات</h2></div>${ints.length?`<div class="grid two">${ints.map(x=>`<div class="card status-row"><span><i class="dot ${x.status==='healthy'?'good':'warn'}"></i>${esc(x.integration_key||x.integration_type)}</span><b>${esc(x.status)}</b></div>`).join('')}</div>`:empty()}<div class="section-title"><h2>الأتمتة الأخيرة</h2></div>${table(['المهمة','الحالة','الموعد','المحاولات'],jobs.map(x=>`<tr><td>${esc(x.job_type)}</td><td>${esc(x.status)}</td><td>${dt(x.scheduled_for)}</td><td>${fmt(x.attempt_count)}/${fmt(x.max_attempts)}</td></tr>`))}<div class="section-title"><h2>الاحتفاظ والإحالات</h2></div>${table(['النوع','الحالة','السبب/الكود','التاريخ'],[...ret.map(x=>({a:x.action_type,b:x.status,c:x.reason,d:x.created_at})),...refs.map(x=>({a:'referral',b:x.status,c:x.code,d:x.created_at}))].map(x=>`<tr><td>${esc(x.a)}</td><td>${esc(x.b)}</td><td>${esc(x.c||'—')}</td><td>${dt(x.d)}</td></tr>`))}`}}
const titles={overview:'مركز الإيرادات',crm:'CRM',conversations:'المحادثات',roi:'ROI',trial:'التجربة المجانية',billing:'الاشتراك والفوترة',automation:'الأتمتة والتكاملات'};
function render(name='overview'){badge();document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));const el=document.getElementById(name);el.innerHTML=views[name]();el.classList.add('active');$('#pageTitle').textContent=titles[name];history.replaceState(null,'','#'+name)}
async function boot(){const {data:{session}}=await sb.auth.getSession();if(!session){location.replace('/login-v2.html');return}try{const r=await fetch(`${URL}/functions/v1/dashboard-data`,{headers:{Authorization:`Bearer ${session.access_token}`}});const j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP_${r.status}`);state=j;$('#tenantName').textContent=state.tenant?.name||'Vaultify';$('#role').textContent=`${state.membership?.role||'member'} · ${state.user?.email||''}`;$('#avatar').textContent=(state.user?.email||'V')[0].toUpperCase();$('#loading').classList.add('hidden');$('#appRoot').classList.remove('hidden');render(location.hash.slice(1) in views?location.hash.slice(1):'overview')}catch(e){$('#loading').innerHTML=`تعذر فتح اللوحة: ${esc(e.message||e)}<br><a href="/login-v2.html">إعادة تسجيل الدخول</a>`}}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)render(b.dataset.view)});$('#logout').addEventListener('click',async()=>{await sb.auth.signOut();location.replace('/login-v2.html')});boot();